### PR TITLE
Move queries into typst dir

### PR DESCRIPTION
**Pull request by TheZoq2**
As discussed in #2

### CODE REVIEW

**Comment by frozolotl** [comment]
Thanks for the PR!

I personally don't like the duplication of the query files.
It seems reasonable to do one of two things:
1. Remove the files `queries/*.scm`. This might break things on update, but I think that is okay.
2. Symlink one file to the other. That should be backwards compatible and seems like the most prudent choice to me, provided nvim-treesitter does handle them correctly.

I prefer the second approach, but I would accept the first one as well. What do you think?

**Comment by TheZoq2** [comment]
Oh oops, I meant to remove them but I guess `git add *` didn't do that. A symlink sounds good, though IIRC there are problems with symlinks on windows :thinking:

**Comment by frozolotl** [comment]
> Oh oops, I meant to remove them but I guess `git add *` didn't do that. A symlink sounds good, though IIRC there are problems with symlinks on windows 🤔

In that case, deletion seems preferable.

**Comment by frozolotl** [comment]
Thanks!

**Pull request merged**
